spring:
  datasource:
    url: jdbc:postgresql://db:5432/cafeteria_bd
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always